Task5
rustamakhmetov/qna2017 pull request #3
Opened 2017-06-01 19:41 UTC by rustamakhmetov

Задание к уроку "Интеграционное (acceptance) тестирование"

2017-06-02 07:48 UTC, vkurennov requested changes

2017-06-02 07:48 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, except: [:index, :show]
Нам не нужны экшены index, show, а также new для ответов, т.к. это все происходит на странице вопроса

2017-06-02 07:48 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      flash_message :notice, @answer.errors.full_messages
Не стоит выводить ошибки валидации через флеш. Сделай универсальный паршл для ошибок и используй его в формах

2017-06-02 07:48 UTC, vkurennov commented on app/controllers/answers_controller.rb
>      @answer.destroy
Тут должна быть проверка на автора. Если она есть в видах, то этого недостаточно, потому что легко сделать запрос напрямую. В контроллерах всегда должна быть проверка прав.

2017-06-02 07:48 UTC, vkurennov commented on app/controllers/questions_controller.rb
>      @question.destroy
Тут должна быть проверка на автора

2017-06-02 07:48 UTC, vkurennov commented on app/views/questions/new.html.slim
> +=form_for @question do |f|
Вот сюда нужно добавить вывод ошибок валидации.

2017-06-02 07:48 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if current_user && current_user.author_of?(@question)
Можно использовать safe navigation из ruby 2.3 и выше, тогда достаточно писать: `current_user&.author_of?(@question)`

2017-06-02 07:48 UTC, vkurennov commented on app/views/questions/show.html.slim
> += form_for [@question, @answer] do |f|
И вот тут надо выводить ошибки валидации через универсальный паршл.

2017-06-02 07:48 UTC, vkurennov commented on config/routes.rb
> +    resources :answers, shallow: true, except: [:index, :show, :new]
Вот видишь, сам указал, что этих экшенов нет, при этом их код в контроллере есть

2017-06-02 07:48 UTC, vkurennov commented on spec/acceptance/answers/write_answer_to_question_spec.rb
> +  scenario 'Authenticated user answer to question' do
Нужен сценарий на невалидный ответ. Все валидации проверять не нужно (это мы делаем в моделях), но важно проверить, что система сообщила юзеру об этих ошибках

2017-06-02 07:48 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Нужно проверить наличие заголовка и тела вопроса на странцие

2017-06-02 07:48 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +feature 'Create question', %q{
Нужен сценарий на невалидный вопрос

2017-06-02 07:48 UTC, vkurennov commented on spec/acceptance/questions/view_question_and_associated_answers_spec.rb
> +      expect(page).to have_content answer.body
у ответов в фабриках также должны быть уникальные тела, как и у вопросов. Иначе, тест будет ложно-положительный

2017-06-02 07:48 UTC, vkurennov commented on spec/acceptance/removal_author_questions_and_answers_spec.rb
> +  given(:user) do
Используй однострочные блоки для таких коротких операций

2017-06-02 07:48 UTC, vkurennov commented on spec/acceptance/removal_author_questions_and_answers_spec.rb
> +  given(:question) do
И тут тоже однострочник используй

2017-06-02 07:48 UTC, vkurennov commented on spec/acceptance/removal_author_questions_and_answers_spec.rb
> +  scenario 'Authenticated author delete your answer' do
Удаление ответов - это отдельная фича, она должна быть в отдельном файле

2017-06-02 07:48 UTC, vkurennov commented on spec/acceptance/removal_author_questions_and_answers_spec.rb
> +  scenario 'Authenticated author can not delete other question' do
Такие же сценарии нужны для незалогиненного юзера

2017-06-02 07:48 UTC, vkurennov commented on spec/acceptance/user_create_questions_and_answers_spec.rb
> +  given(:user) do
Используй однострочники

2017-06-02 07:48 UTC, vkurennov commented on spec/acceptance/user_create_questions_and_answers_spec.rb
> +  scenario 'Authenticated user create question' do
У тебя уже есть подобный тест в create_question_spec.rb, зачем его снова писать?

2017-06-02 07:48 UTC, vkurennov commented on spec/acceptance/user_create_questions_and_answers_spec.rb
> +  scenario 'Authenticated user create answer' do
И этот тест у тебя уже есть

2017-06-02 07:48 UTC, vkurennov commented on spec/acceptance/user_create_questions_and_answers_spec.rb
> +    visit question_path(question)
Это 2 разных сценария, и оба уже есть (а если нет, то они должны быть в соответсвующих спеках)

2017-06-02 07:48 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> -  describe 'GET #index' do
Тестов нет, а экшены в контроллере остались

2017-06-02 07:48 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
Тут надо проверить связь ответа с залогиненным юзером

2017-06-02 07:48 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +
Тут должно быть 2 контекста: для автора и для не-автора

2017-06-02 07:48 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>          expect { post :create, params: { question: attributes_for(:question) }}.to change(Question, :count).by(1)
Тут нужно проверить связь вопроса с залогиненным юзером

2017-06-02 07:48 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +
Тут должно быть 2 контекста: для автора и для не-автора

2017-06-02 09:39 UTC, rustamakhmetov commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, except: [:index, :show]
сделано

2017-06-02 11:55 UTC, rustamakhmetov commented on app/controllers/answers_controller.rb
> +      flash_message :notice, @answer.errors.full_messages
сделано

2017-06-04 12:56 UTC, rustamakhmetov commented on app/controllers/answers_controller.rb
>      @answer.destroy
сделано

2017-06-04 16:27 UTC, rustamakhmetov commented on app/controllers/questions_controller.rb
>      @question.destroy
сделано

2017-06-04 16:28 UTC, rustamakhmetov commented on app/views/questions/new.html.slim
> +=form_for @question do |f|
сделано

2017-06-04 16:37 UTC, rustamakhmetov commented on app/views/questions/show.html.slim
> +- if current_user && current_user.author_of?(@question)
сделано

2017-06-04 16:37 UTC, rustamakhmetov commented on app/views/questions/show.html.slim
> += form_for [@question, @answer] do |f|
сделано

2017-06-04 16:39 UTC, rustamakhmetov commented on config/routes.rb
> +    resources :answers, shallow: true, except: [:index, :show, :new]
код в контроллере - удален

2017-06-04 16:45 UTC, rustamakhmetov commented on spec/acceptance/removal_author_questions_and_answers_spec.rb
> +  given(:user) do
сделано

2017-06-04 16:46 UTC, rustamakhmetov commented on spec/acceptance/removal_author_questions_and_answers_spec.rb
> +  given(:question) do
сделано

2017-06-04 16:46 UTC, rustamakhmetov commented on spec/acceptance/user_create_questions_and_answers_spec.rb
> +  given(:user) do
сделано

2017-06-04 16:46 UTC, rustamakhmetov commented on spec/controllers/answers_controller_spec.rb
> -  describe 'GET #index' do
сделано

2017-06-04 16:47 UTC, rustamakhmetov commented on spec/controllers/answers_controller_spec.rb
> +
сделано

2017-06-04 16:47 UTC, rustamakhmetov commented on spec/controllers/questions_controller_spec.rb
> +
сделано

2017-06-04 17:11 UTC, rustamakhmetov commented on spec/acceptance/answers/write_answer_to_question_spec.rb
> +  scenario 'Authenticated user answer to question' do
сделано

2017-06-04 17:18 UTC, rustamakhmetov commented on spec/acceptance/questions/create_question_spec.rb
> +feature 'Create question', %q{
сделано

2017-06-04 17:18 UTC, rustamakhmetov commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
сделано

2017-06-04 17:27 UTC, rustamakhmetov commented on spec/acceptance/questions/view_question_and_associated_answers_spec.rb
> +      expect(page).to have_content answer.body
сделано

2017-06-04 17:34 UTC, rustamakhmetov commented on spec/acceptance/removal_author_questions_and_answers_spec.rb
> +  scenario 'Authenticated author delete your answer' do
сделано

2017-06-04 18:51 UTC, rustamakhmetov commented on spec/acceptance/removal_author_questions_and_answers_spec.rb
> +  scenario 'Authenticated author can not delete other question' do
сделано

2017-06-04 18:55 UTC, rustamakhmetov commented on spec/acceptance/user_create_questions_and_answers_spec.rb
> +  scenario 'Authenticated user create question' do
убран повтор

2017-06-04 18:55 UTC, rustamakhmetov commented on spec/acceptance/user_create_questions_and_answers_spec.rb
> +  scenario 'Authenticated user create answer' do
убран повтор

2017-06-04 18:55 UTC, rustamakhmetov commented on spec/acceptance/user_create_questions_and_answers_spec.rb
> +    visit question_path(question)
убран повтор

2017-06-04 19:17 UTC, rustamakhmetov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
сделано

2017-06-05 05:14 UTC, rustamakhmetov commented on spec/controllers/questions_controller_spec.rb
>          expect { post :create, params: { question: attributes_for(:question) }}.to change(Question, :count).by(1)
сделано

2017-06-05 06:05 UTC, webmstk commented on app/controllers/answers_controller.rb
> +      flash_message :notice, @answer.errors.full_messages.join("<br>")
Флеши - короткие сообщения системы. Как правило, они нужны для обратной связи пользователю - сообщение, о том, что что-то было сделано. Или не было сделано.

Валидационные ошибки обычно не передают во флеш. Форма может быть большая, а ошибок много, и это не совсем вписывается в концепцию  флеш-сообщений :)

2017-06-05 06:05 UTC, webmstk commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.new(answer_params.merge(user: current_user))
вот ещё вариант
```
@answer = @question.answers.new(answer_params)
@answer.user = current_user
```

2017-06-05 06:05 UTC, webmstk commented on app/controllers/questions_controller.rb
> +      @question.destroy
Если нет проверки выполняемого действия (`if @question.destroy ... else ...`), то лучше использовать `destroy!`. Если действие не выполнится, то ты об этом узнаешь (выбросится исключение).

2017-06-05 06:05 UTC, webmstk commented on app/models/user.rb
> +    model.user_id == id if model.respond_to?(:user_id)
Не надо проверки, пусть падает. Иначе нельзя будет полагаться на возвращаемый результат. Метод для корректной работы требует, чтобы переданный объект имел пользователя. И лучше узнать сразу о том, что метод используется неправильно (или что переданный объект не тот или не такой), чем потом дебажить :)

2017-06-05 06:17 UTC, rustamakhmetov commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.new(answer_params.merge(user: current_user))
раньше так и было...
не знаю какой вариант лучше...

2017-06-05 06:43 UTC, webmstk commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.new(answer_params.merge(user: current_user))
дело вкуса, хотя двухстрочный вариант я встречаю чаще :)

2017-06-05 08:30 UTC, vkurennov approved these changes

2017-06-05 08:30 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@answer.question_id), notice: "Вы не можете удалять чужие ответы."
Редиректы одинаковые, только сообщение меняется. Лучше редирект вынести из условия, оставив в нем только установку сообщений

2017-06-05 08:30 UTC, vkurennov commented on app/models/user.rb
> +    model.user_id == id if model.respond_to?(:user_id)
На самом деле это тоже корректный вариант, что, если мы не хотим, чтобы в этом методе что-то падало? Но если у объекта нет user_id, то точно юзер не может быть автором этого объекта. Так что, имхо, вполне нормальный код. Хотя, конечно, с т.з. дебага могуть быть неприятности.

2017-06-05 08:30 UTC, vkurennov commented on spec/acceptance/answers/write_answer_to_question_spec.rb
> +  scenario 'Залогиненный пользователь пишет невалидный ответ на вопрос' do
Лучше все же по-английски писать заголовки сценариев, русский язык в коде выглядит непрофессионально. Тем более, что почти все сценарии на английском, а тут один на русском.

2017-06-05 08:30 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    it 'Только автор вопроса может его удалить' do
Опять русский, переведи хотя бы google translate, все равно надо английский тренировать

2017-06-05 08:40 UTC, webmstk commented on app/models/user.rb
> +    model.user_id == id if model.respond_to?(:user_id)
В тех контекстах, в которых мы собираемся использовать этот метод, мне кажется, что вариант без проверки будет полезней, но я согласен, можно и так :)

2017-06-05 08:46 UTC, rustamakhmetov commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@answer.question_id), notice: "Вы не можете удалять чужие ответы."
сделано

2017-06-05 08:46 UTC, rustamakhmetov commented on spec/acceptance/answers/write_answer_to_question_spec.rb
> +  scenario 'Залогиненный пользователь пишет невалидный ответ на вопрос' do
исправлено

2017-06-05 08:47 UTC, rustamakhmetov commented on spec/controllers/questions_controller_spec.rb
> +    it 'Только автор вопроса может его удалить' do
исправлено

2017-06-05 08:55 UTC, merged